### ISSUE TITLE
cannot find...`Json` in module `content`

### ISSUE THREAD

**Issue by noneofyourbusiness1415252** [tonkku107/slashook#12]
This error occurs when compiling:
```rs
error[E0425]: cannot find function, tuple struct or tuple variant `Json` in module `content`
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/slashook-0.2.0/src/webhook/mod.rs:43:25
   |
43 |         .merge(content::Json(json.to_string()).respond_to(req)?)
   |                         ^^^^ not found in `content`
   ```
It's using rocket v0.5.0-rc.2 (the version is automatically updated to the later minor version, so it won't stay v0.5.0-rc.1), in which it seems to be [`RawJson`](https://docs.rs/rocket/0.5.0-rc.2/rocket/response/content/struct.RawJson.html), not `Json`

**Comment by noneofyourbusiness1415252** [comment]
The rocket version is specified as `v0.5.0-rc.1`, but it will automatically use the later minor version, `v0.5.0-rc.2`. The latest version of rocket [uses `Json`](https://docs.rs/rocket/latest/rocket/response/content/struct.Json.html)

**Comment by tonkku107** [comment]
It seems rocket internally has the same issue so locking to a previous version is not possible...

**Comment by tonkku107** [comment]
Version 0.2.1 released
